import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import ApplicationRepo from "@/app/repo/application-repo";

const appRepo = new ApplicationRepo();

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="banner">
          <div className="container">
            <div className="banner-content">
              <div className="logo">
                <i className="fas fa-briefcase"></i>
                <span>JobBoard</span>
              </div>
              <div class="banner-stats">
                <div class="stat-item">
                  <i class="fas fa-building"></i>
                  <span id="totalJobs">{appRepo.getActiveJobsCount()}</span>
                  <span class="stat-label">Active Jobs</span>
                </div>
                <div class="stat-item">
                  <i class="fas fa-file-alt"></i>
                  <span id="totalApplications">
                    {appRepo.getApplicationsCount()}
                  </span>
                  <span class="stat-label">Applications</span>
                </div>
              </div>
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
